service: prezet-com

provider:
  name: aws
  region: us-east-1
  stage: 'prod'
  apiGateway:
    binaryMediaTypes:
      - 'image/webp'
  environment:
    APP_KEY: ${ssm:/prezet-com/APP_KEY}
    TORCHLIGHT_TOKEN: ${ssm:/prezet-com/TORCHLIGHT_TOKEN}
    APP_ENV: production
    APP_NAME: prezet-com
    APP_URL: https://prezet.com
    SESSION_DRIVER: array
    CACHE_STORE: array
    BREF_BINARY_RESPONSES: '1'
    PREZET_FILESYSTEM_DISK: s3
    AWS_BUCKET: !Ref PrezetBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:*
          Resource:
            - !Sub '${PrezetBucket.Arn}'
            - !Sub '${PrezetBucket.Arn}/*'

resources:
  Resources:
    PrezetBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: prezet-com-prezet-storage

package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'

functions:
  web:
    handler: public/index.php
    runtime: php-83-fpm
    reservedConcurrency: 10
    timeout: 28
    layers:
      - ${bref-extra:gd-php-83}
    events:
      - httpApi: '*'

  artisan:
    handler: artisan
    runtime: php-83-console
    reservedConcurrency: 5
    timeout: 720

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
  - serverless-lift
  - serverless-s3-sync
  - serverless-api-gateway-throttling

constructs:
  website:
    domain: prezet.com
    certificate: arn:aws:acm:us-east-1:221576664686:certificate/af989412-c8c5-443d-92a2-4d18efe53d68
    type: server-side-website
    assets:
      '/build/*': public/build
      '/favicon.ico': public/favicon.ico
      '/favicon.svg': public/favicon.svg
      '/ogimage.png': public/ogimage.png
      '/robots.txt': public/robots.txt
      '/prezet_sitemap.xml': public/prezet_sitemap.xml

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 20
    maxConcurrentRequests: 10
  s3Sync:
    - bucketName: prezet-com-prezet-storage
      localDir: storage/prezet
      deleteRemoved: true
